### ISSUE TITLE
Author's story page

### ISSUE THREAD

**Issue by kindacoder** [she-endeavors/SheE#10]
**Brief description of the feature? Please describe.**
Author's story  page.
**Links and resources**
[https://adobe.ly/2FIRXnx](https://adobe.ly/2FIRXnx)
**Screenshots for the new feature**
[https://adobe.ly/2FIRXnx](https://adobe.ly/2FIRXnx)
**Additional Information**
NA

**Comment by Ash-D23** [comment]
i would like to work on this issue can you please explain what i have to do, i am new to this project

**Comment by vaibhav-sharma-frontend** [comment]
@kindacoder  can I take this issue.

**Comment by kindacoder** [comment]
@asha15 can you please look into this ?

**Comment by asha15** [comment]
@kindacoder  can i get more information about this issue?

**Comment by asha15** [comment]
@kindacoder shall i work on this?

**Comment by vaibhav-sharma-frontend** [comment]
> @kindacoder can I take this issue.

can I take this issue?
@kindacoder @prithaupadhyay

**Comment by prithaupadhyay** [comment]
@vsharma20v Yes please. Go for it.
