### ISSUE TITLE
Develop an HTML page for "All Stories"

### ISSUE THREAD

**Issue by prithaupadhyay** [she-endeavors/SheE#14]
### Brief description of the feature? 
You need to develop an HTML page for "All Stories" section, where all the stories will be displayed separated by their categories. Use Bootstrap for implementing the design. 
You need to refer to the designed mockup, as mentioned below.
### Links and resources
[Wireframe](https://xd.adobe.com/view/da8357fa-7130-4652-8f5b-161ee246a39e/)
#### Mockup
![web_1920_____1-1](https://user-images.githubusercontent.com/21213021/56080672-83d1b080-5e21-11e9-82f7-d04e8b35dc37.png)

**Comment by vaibhav-sharma-frontend** [comment]
@prithaupadhyay  can I work on this issue?

**Comment by prithaupadhyay** [comment]
@vsharma20v Yes please. Go ahead.

**Comment by vaibhav-sharma-frontend** [comment]
@prithaupadhyay @kindacoder I have created the PR #17
