### ISSUE TITLE
Add responsiveness to the Login Page

### ISSUE THREAD

**Issue by prithaupadhyay** [she-endeavors/SheE#24]
https://she-endeavors.github.io/SheE/login

Login Page should be responsive.

**Comment by vaibhav-sharma-frontend** [comment]
@prithaupadhyay can you assign this issue to me?

**Comment by prithaupadhyay** [comment]
@asha15 Have you completed working on this issue?

**Comment by asha15** [comment]
@prithaupadhyay  yes
