### ISSUE TITLE
Login button hover produces an abrupt effect

### ISSUE THREAD

**Issue by vaibhav-sharma-frontend** [she-endeavors/SheE#27]
Login button hover produces an abrupt effect.

**Description**: When you hover over the Login button in Login.html page then there is an abrupt movement of the content above and below the login button.

**Screenshot**:
![she](https://user-images.githubusercontent.com/31318828/57974637-37a5fd00-79d9-11e9-9924-87ecd0fe878a.gif)

**Comment by vaibhav-sharma-frontend** [comment]
@prithaupadhyay @kindacoder 
I'm giving it a new look also
Screenshot:
![Screenshot from 2019-05-19 04-09-29](https://user-images.githubusercontent.com/31318828/57975705-14387d80-79ec-11e9-8745-9fedb22617da.png)


Give your opinion on the new look also.

**Comment by kindacoder** [comment]
> @prithaupadhyay @kindacoder
> I'm giving it a new look also
> Screenshot:
> ![Screenshot from 2019-05-19 04-09-29](https://user-images.githubusercontent.com/31318828/57975705-14387d80-79ec-11e9-8745-9fedb22617da.png)
> 
> Give your opinion on the new look also.

@vsharma20v can you please paste the screenshot of mobile view ?

**Comment by vaibhav-sharma-frontend** [comment]
@kindacoder I'm working on its responsiveness so I will give its mobile view till today's evening

**Comment by prithaupadhyay** [comment]
@vsharma20v I really like the new look. Lets wait for @kindacoder suggestions on this.

**Comment by vaibhav-sharma-frontend** [comment]
@prithaupadhyay @kindacoder I made it responsive have a look
screenshots:
![Screenshot from 2019-05-19 20-29-33](https://user-images.githubusercontent.com/31318828/57984036-2dd1d780-7a75-11e9-8691-c358d2a6cdc1.png)
![Screenshot from 2019-05-19 20-29-41](https://user-images.githubusercontent.com/31318828/57984037-2e6a6e00-7a75-11e9-937e-a7f1aa583269.png)
![Screenshot from 2019-05-19 20-29-45](https://user-images.githubusercontent.com/31318828/57984038-2e6a6e00-7a75-11e9-83bc-421dde2c9099.png)
![Screenshot from 2019-05-19 20-29-59](https://user-images.githubusercontent.com/31318828/57984039-2f030480-7a75-11e9-9100-0e2f55f39750.png)
![Screenshot from 2019-05-19 20-30-01](https://user-images.githubusercontent.com/31318828/57984040-2f030480-7a75-11e9-8594-2f124e6ad196.png)


**Mobile View**
![_home_vaibhav_Desktop_SheE%20GSSoC_SheE_login html(iPhone 6_7_8) (1)](https://user-images.githubusercontent.com/31318828/57984046-4215d480-7a75-11e9-9ea9-d6afd91f3bb8.png)
![_home_vaibhav_Desktop_SheE%20GSSoC_SheE_login html(iPhone 6_7_8) (2)](https://user-images.githubusercontent.com/31318828/57984047-42ae6b00-7a75-11e9-804b-84c707086b6b.png)

**Comment by kindacoder** [comment]
@vsharma20v  Awesome design. Let me merge it :+1:
