### ISSUE TITLE
Change the Menus and Add logo 

### ISSUE THREAD

**Issue by kindacoder** [she-endeavors/SheE#3]
**Brief description of the feature? Please describe.**
Change the Menus and Logo of the website similar to old website.

**Links and resources**
Link for the old website- [web](http://sheendeavors.org/)
Link for logo - [http://sheendeavors.org/images/logo-100.png](http://sheendeavors.org/images/logo-100.png)
**Screenshots for the new feature**
NA.
Please check old website.
**Additional Information**
NA

**Comment by Manvityagi** [comment]
Can I work on this issue ?

**Comment by kindacoder** [comment]
sure @Manvityagi

**Comment by kindacoder** [comment]
hey @Manvityagi what is the status for this one ?

**Comment by Manvityagi** [comment]
@kindacoder PR sent! Let me know if any other changes have to be done.
