### ISSUE TITLE
Develop author details page 

### ISSUE THREAD

**Issue by kindacoder** [she-endeavors/SheE#6]
**Brief description of the feature? Please describe.**
In this issue, write story page need to be developed. write story page contains -

- Trending stories (right corner )
- bookmark story 
- total no of shares
- share story
- story details
- author details
- comments

**Links and resources**
[link to the wireframe](http://bit.ly/she-author-page)
**Screenshots for the new feature**
[screenshot](http://bit.ly/she-author-page)

**Additional Information**
NA

**Comment by shreyarastogi** [comment]
I am interested in working,but can you please tell me whether we just have to design or implement all the functionalities i.e. backend as well??

**Comment by kindacoder** [comment]
No, as we discussed earlier, we are only working on front-end part as of now. are you familiar with node ?

**Comment by kindacoder** [comment]
@shreyarastogi you only have to design front-end part as of now

**Comment by asha15** [comment]
may i work on this issue ?

**Comment by kindacoder** [comment]
sure @asha15

**Comment by shreyarastogi** [comment]
@kindacoder  okay, then i would like to work on it.

**Comment by kindacoder** [comment]
@shreyarastogi @asha15 it's author details page

**Comment by asha15** [comment]
@kindacoder Is it okay if two people work on the same issue ?

**Comment by kindacoder** [comment]
yes @asha15 it would be great if you both can divide work. @shreyarastogi

**Comment by shreyarastogi** [comment]
@kindacoder Since i asked first, so i request you to kindly assign it to me, thank you.

**Comment by asha15** [comment]
@kindacoder  @shreyarastogi Then shall i work on first three features?

**Comment by kindacoder** [comment]
> @kindacoder @shreyarastogi Then shall i work on first three features?

Since the issue is big, a lot of development is needed for this one. Since @shreyarastogi asked first, shreya let me know if you can work entirely for this one ?

**Comment by shreyarastogi** [comment]
yes, I can work on it.

**Comment by kindacoder** [comment]
> @kindacoder @shreyarastogi Then shall i work on first three features?

Hi @asha15 , let me create another issue. :)

**Comment by asha15** [comment]
@kindacoder i'm eagerly waiting :)

**Comment by kindacoder** [comment]
@shreyarastogi what is the update ?

**Comment by shreyarastogi** [comment]
I am sorry, haven't been able to work on it, @kindacoder please assign it to someone else.

**Comment by vaibhav-sharma-frontend** [comment]
@prithaupadhyay @kindacoder 
Plz assign me this issue.

**Comment by prithaupadhyay** [comment]
@vsharma20v Yes. Start working on it. Looking forward to your PR
