### ISSUE TITLE
Navbar not working properly on mobile devices

### ISSUE THREAD

**Issue by kindacoder** [she-endeavors/SheE#7]
#3 Navbar not working on mobile devices.

**Comment by Hansika716** [comment]
I would like to work on it

**Comment by kindacoder** [comment]
sure @codehansika

**Comment by KanchanThareja** [comment]
Can i take this issue? @kindacoder

**Comment by kindacoder** [comment]
@KanchanThareja sure :)

**Comment by kindacoder** [comment]
just make sure that it completes today :+1:
